all:
  groups:
    webservers:
      hosts:
        web-prod-01:
          ansible_host: 127.0.0.1
          ansible_port: 2222
          ansible_user: deployer
    databases:
      hosts:
        db-master:
          ansible_host: 127.0.0.1
          ansible_port: 2223
          ansible_user: postgres
    ubuntu:
      hosts:
        ubuntu-prod-01:
          ansible_host: 127.0.0.1
          ansible_port: 2225
          ansible_user: ubuntu
    centos:
      hosts:
        centos-prod-01:
          ansible_host: 127.0.0.1
          ansible_port: 2226
          ansible_user: centos
    sudo-password:
      hosts:
        sudopw-prod-01:
          ansible_host: 127.0.0.1
          ansible_port: 2227
          ansible_user: ubuntu
